name: Periodic Hello

on:
  workflow_dispatch:
  schedule:
    - cron: '*/15 * * * *'

jobs:
  say_hello:
    runs-on: ubuntu-latest
    steps:
      - name: Say Hello
        run: echo 'hello!'
  health_check:
    runs-on: ubuntu-latest
    steps:
      - name: pokedex_health_check
        uses: jtalk/url-health-check-action@v5
        with:
          url: https://full-stack-open-pokedex-vua6.onrender.com/health
          max-attempts: 3
