name: Deployment pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches: [main]
    types: [opened, synchronize]

jobs:
  simple_deployment_pipeline:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v6
        with:
          node-version: '24'
      - name: Install dependencies
        run: npm install
      - name: Check style
        run: npm run eslint
      - name: Run npm test
        run: npm run test
      - name: Run npm build
        run: npm run build
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
      - name: Run Playwright tests
        run: npm run test:e2e
      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
      - name: Trigger deployment
        if: ${{ github.event_name == 'push' && !contains(join(github.event.commits.*.message, ','), '#skip') }}
        run: curl ${{ secrets.RENDER_DEPLOY_HOOK }}
  tag_release:
    if: ${{ github.event_name == 'push' && !contains(join(github.event.commits.*.message, ','), '#skip') }}
    needs: [simple_deployment_pipeline]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Bump version and push tag
        uses: anothrNick/github-tag-action@4ed44965e0db8dab2b466a16da04aec3cc312fd8
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BUMP: patch
  notification:
    if: ${{ always() && github.event_name == 'push' }}
    needs: [simple_deployment_pipeline]
    runs-on: ubuntu-latest
    steps:
      - name: Success Notification
        if: ${{ success() }}
        uses: sarisia/actions-status-discord@v1
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
          nodetail: true
          status: ${{ job.status }}
          content: '✅ **Deployment Successful** A new version deployed to production'
          title: Deployment Details
          description: |
            **Commit:** ${{ github.sha }}
            **Message:** ${{ github.event.head_commit.message}}
            **Author:** ${{ github.event.head_commit.author.name }}
      - name: Build Failed
        uses: sarisia/actions-status-discord@v1
        if: ${{ failure() }}
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK}}
          nodetail: true
          status: ${{ job.status }}
          content: '❌ **Build Failed!** The pipeline encountered an error'
          title: Failure Details
          description: |
            **Repository:** ${{ github.action_repository}}
            **Branch:** ${{ github.ref_name}}
            **Commit:** ${{ github.sha }}
            **Message:** ${{ github.event.head_commit.message }}
            **Author:** ${{ github.event.head_commit.author.name }}
            **Workflow:** ${{ github.workflow }}
            **Job:** ${{ github.job }}

            [View Commit](${{ github.event.head_commit.url}})
            [View Workflow Run](${{ github.workflow}})
